services:
  - type: web
    name: fastapi-backend
    env: python
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comet-db
          property: connectionString
databases:
  - name: comet-db
    databaseName: comet
    user: comet_user
